### ISSUE TITLE
Plugin crash in Webstorm

### ISSUE THREAD

**Issue by jkrehm** [giraud/reasonml-idea-plugin#337] opened 2021-07-16 13:54 UTC
plugin version: 0.102-2021.1

### Description

When I open a Reason file in Webstorm 2021.1.3 the plugin crashes with this stacktrace:

```
java.lang.NoClassDefFoundError: com/intellij/psi/impl/source/tree/java/PsiLiteralExpressionImpl
	at com.reason.lang.core.psi.PsiLiteralExpression$StringLiteralEscaper.decode(PsiLiteralExpression.java:52)
	at com.intellij.httpClient.http.security.HttpUrlsUsageInspection.decodeLiteralValue(HttpUrlsUsageInspection.kt:198)
	at com.intellij.httpClient.http.security.HttpUrlsUsageInspection.getLiteralFragments(HttpUrlsUsageInspection.kt:133)
	at com.intellij.httpClient.http.security.HttpUrlsUsageInspection.access$getLiteralFragments(HttpUrlsUsageInspection.kt:26)
	at com.intellij.httpClient.http.security.HttpUrlsUsageInspection$buildVisitor$1.visitElement(HttpUrlsUsageInspection.kt:69)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.accept(LeafPsiElement.java:208)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:346)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:174)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:132)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:121)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$10(LocalInspectionsPass.java:346)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1091)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:61)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitRestElementsAndCleanup(LocalInspectionsPass.java:366)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:208)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:119)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl PluginClassLoader(plugin=PluginDescriptor(name=ReasonML, id=reasonml, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/WebStorm/ch-0/211.7628.25.plugins/reasonml-idea-plugin, version=0.102-2021.1, package=null), packagePrefix=null, instanceId=111, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 48 more
```
The stacktrace seems similar to #333, but in WebStorm vs CLion.

In case it matters, I'm running Webstorm on Linux Mint 20.

**Comment by giraud** [comment] 2021-07-21 06:01
333 is fixed in 0.102.1 , you have 0.102.
I can't reproduce with 0.102.1

**Comment by ktrzos** [comment] 2021-07-21 06:44
@giraud 

I'm receiving such error in PhpStorm 2021.1.4 when having the plugin in 0.102-2021-1 version. Was trying to check if there is an update, but there is none :(.

BTW. "Plugin Homepage" link (plugin profile in IDE) does not work when clicking on it. It is forwarding me to a https://plugins.jetbrains.com/plugin/9440-reasonml address and later on on https://plugins.jetbrains.com/legal/verification-error.

**Comment by giraud** [comment] 2021-07-21 09:02
I dont reproduce locally with phpstorm 2021.1.4. maybe you can try to uninstall then reinstall the plugin ?

**Comment by jkrehm** [comment] 2021-07-21 14:53
WebStorm would not automatically update to 0.102.1, even when I used "Check for plugin updates...". I had to uninstall and reinstall the plugin to get the latest version. I can confirm that I don't get the error with 0.102.1.

**Closed** 2021-07-21 15:29 UTC

**Comment by ktrzos** [comment] 2021-07-22 06:28
I also confirm, that the error stopped to appear after plugin reinstall.
