### ISSUE TITLE
End of comments containing quotes not always detected

### ISSUE THREAD

**Issue by jfehrle** [giraud/reasonml-idea-plugin#421] opened 2023-08-04 21:02 UTC
plugin version: 0115-beta01-2023.1

### Description

1. Open a new file, e.g. **junk.ml**, type a valid statement such as `let _ = ()`.  Observe that the **let** keyword is highlighted in dark blue.

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/2856f091-54c8-4907-8139-f383044b1c7f)

2. Add `(* "rest" *)` above the current line.  Expected: the **let** should still be highlighted.  Actual: the **let** is in the grey used for comments.

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/c2143d99-9218-4c42-94e9-d57ce3e6fe9f)

3.  Incrementally editing the first line gives strange, maybe not entirely repeatable results, e.g.

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/59fa87bf-c51e-4a31-a5f1-cba97d929386)

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/81382d34-7dee-4cd0-a461-6269b1d0bf33)

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/566b0b8c-1960-4cd6-baf2-3c405afaeeea)

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/973e94ee-d8c3-4737-8467-c3f1b2af780e)

![image](https://github.com/giraud/reasonml-idea-plugin/assets/1253341/033ebc65-db50-49c9-954e-86e81a791bbc)

**Comment by jfehrle** [comment] 2023-08-04 21:07
PS When I run into the problem in the middle of a large file, the rest of the file is then treated as comments.  Usually I just close and reopen the editor window to recover.  Slightly distracting.

**Comment by giraud** [comment] 2023-08-22 15:44
I see, OCaml is particularly annoying with comments !!! root cause comes from the fix of #99 😡

**Comment by giraud** [comment] 2023-08-22 15:46
#99 is the root cause

**Comment by jfehrle** [comment] 2023-08-22 18:59
Not in the 0.115 release, right?

**Comment by giraud** [comment] 2023-08-23 06:01
no. 0.155 was released to fix perf problems.

**Comment by giraud** [comment] 2023-08-31 07:12
Initialisation bug is fixed in 0.116

**Closed by giraud** 2023-08-31 07:12 UTC

**Comment by jfehrle** [comment] 2023-08-31 20:11
Looks good, thanks!
